AWSTemplateFormatVersion: 2010-09-09

Resources:
  ProfileManagementLambda:
    Type: AWS::Lambda::Function
    DependsOn:
    - LambdaRole
    Properties:
      FunctionName: profilemngmt
      Handler: profile.lambda_handler
      PackageType: Zip
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Code:
        S3Bucket: !ImportValue 'packagebucket-export'
        S3Key: mypackage.zip

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'profilerole'
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: 's3_policy'
          PolicyDocument:
            Statement :
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource : 'arn:aws-cn:s3:::packagebucket'
        - PolicyName: 'clowdwatch_policy'
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws-cn:logs:cn-northwest-1:803468271100:log-group:/aws/lambda/*:*:*"
        - PolicyName: 'dynamodb_policy'
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                Resource: "arn:aws-cn:dynamodb:cn-northwest-1:803468271100:table/Profile"

  ProfileManagementBucket:
#    DeletionPolicy : Retain
    Type : AWS::S3::Bucket
    Description : Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName : csv-profile-management
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: csv
            Function: !GetAtt [ProfileManagementLambda, Arn]
      BucketEncryption:
        ServerSideEncryptionConfiguration :
          - ServerSideEncryptionByDefault :
              SSEAlgorithm : AES256

  PermissionForS3ToInvokeLambda:
    Type: AWS::Lambda::Permission
    DependsOn: ProfileManagementLambda
    Properties:
      FunctionName:
        Fn::GetAtt:
          - ProfileManagementLambda
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws-cn:s3:::csv-profile-management
